/- Copyright 2022 ACL & MIdFF
! This file was ported from Lean 3 source module divided_powers.dp_algebra.misc
-/

import Mathlib.Algebra.MvPolynomial.Supported
import Mathlib.Algebra.RingQuot
import Mathlib.Algebra.TrivSqZeroExt
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous

noncomputable section

open Finset MvPolynomial RingQuot DirectSum Ideal Ideal.Quotient

theorem Ideal.pow_eq_bot {R : Type _} [CommSemiring R] [NoZeroDivisors R]
    {I : Ideal R} {n : ℕ} (hn : n ≠ 0) :
  I ^ n = ⊥ ↔ I = ⊥ := by
  induction' n with n ih
  · exfalso; exact hn (Eq.refl _)
  · by_cases hn0 : n = 0
    · rw [hn0, pow_one]
    · rw [pow_succ, mul_eq_bot, ih hn0, or_self_iff]

namespace MvPolynomial

variable {R S σ : Type _} [CommSemiring R] [CommSemiring S]

@[simp]
theorem eval₂Hom.smul (f : R →+* S) (g : σ → S) (r : R) (P : MvPolynomial σ R) :
    eval₂Hom f g (r • P) = f r • eval₂Hom f g P := by
  simp only [smul_eq_C_mul, coe_eval₂Hom, eval₂_mul, eval₂_C, Algebra.id.smul_eq_mul]

variable [Algebra R S]

variable (R)

/-- `MvPolynomial.eval₂ (algebraMap R S) g` as an `R`-algebra homomorphism. -/
def eval₂AlgHom (g : σ → S) : MvPolynomial σ R →ₐ[R] S :=
  { eval₂Hom (algebraMap R S) g with
    commutes' := fun r => by rw [RingHom.toFun_eq_coe, coe_eval₂Hom, algebraMap_eq, eval₂_C] }

variable {R}

theorem eval₂AlgHom_apply (g : σ → S) (P : MvPolynomial σ R) :
  eval₂AlgHom R g P = eval₂Hom (algebraMap R S) g P := rfl

@[simp]
theorem coe_eval₂AlgHom (g : σ → S) :
  ⇑(eval₂AlgHom R g) = eval₂ (algebraMap R S) g := rfl

@[simp]
theorem eval₂AlgHom_X' (g : σ → S) (i : σ) :
  eval₂AlgHom R g (X i : MvPolynomial σ R) = g i := eval₂_X (algebraMap R S) g i

end MvPolynomial

section IdealsAndRel

theorem quotient_mk_eq_ofRel {A : Type _} [CommRing A] {r : A → A → Prop}
    {a b : A} (h : r a b) :
  mk (ofRel r) a = mk (ofRel r) b := by
  suffices hinj : Function.Injective (RingQuot.ringQuotEquivIdealQuotient r).invFun by
    apply hinj; exact mkRingHom_rel h
  rw [Function.injective_iff_hasLeftInverse]
  exact ⟨(ringQuotEquivIdealQuotient r).toFun, (ringQuotEquivIdealQuotient r).right_inv⟩

namespace Ideal

theorem quotient_mk_eq_ringQuot_apply (R : Type _) [CommRing R] {A : Type _} [CommRing A]
    [Algebra R A] (r : A → A → Prop) (a : A) :
    mk (ofRel r) a = ringQuotToIdealQuotient r (mkAlgHom R r a) := by
  rw [← ringQuotToIdealQuotient_apply r a, ← mkAlgHom_coe R r]
  rfl

namespace Quotient

variable {R S : Type _} [CommRing R] [CommRing S]

theorem rel_le_ker (I : Ideal R) {r : R → R → Prop} (hr : I = ofRel r) (f : R →+* S)
    (hf : ∀ {a b : R}, r a b → f a = f b) : I ≤ RingHom.ker f := by
  rw [hr, ofRel, Submodule.span_le]
  rintro x ⟨a, b, hx, hab⟩
  rw [eq_sub_iff_add_eq.mpr hab, SetLike.mem_coe, RingHom.mem_ker, map_sub, sub_eq_zero, hf hx]

/-- Given a binary relation `r` on `R` and a ring homomorphism `f : R →+* S` that is constant on
  each equivalent class of `r`, lift `f` to the quotient by the ideal generated by `r`. -/
def liftRel (I : Ideal R) {r : R → R → Prop} (hr : I = ofRel r) (f : R →+* S)
    (hf : ∀ {a b : R}, r a b → f a = f b) : R ⧸ I →+* S :=
  lift I f (rel_le_ker I hr f hf)


end Quotient

end Ideal

end IdealsAndRel

namespace TrivSqZeroExt

variable (R M : Type _) [CommSemiring R] [AddCommMonoid M] [Module R M] [Module Rᵐᵒᵖ M]
  [IsCentralScalar R M]

def kerIdeal : Ideal (TrivSqZeroExt R M) :=
  RingHom.ker (fstHom R R M)

theorem mem_kerIdeal_iff_inr (x : TrivSqZeroExt R M) : x ∈ kerIdeal R M ↔ x = inr x.snd :=
  by
  obtain ⟨r, m⟩ := x
  simp only [kerIdeal, RingHom.mem_ker, fstHom_apply, fst_mk]
  exact ⟨fun hr => by rw [hr]; rfl, fun hrm => by rw [← fst_mk r m, hrm, fst_inr]⟩

theorem mem_kerIdeal_iff_exists (x : TrivSqZeroExt R M) : x ∈ kerIdeal R M ↔ ∃ m : M, x = inr m := by
  rw [mem_kerIdeal_iff_inr]
  exact ⟨fun h => ⟨x.snd, h⟩, fun ⟨m, hm⟩ => by rw [hm]; rfl⟩

theorem sqZero : kerIdeal R M ^ 2 = (⊥ : Ideal (TrivSqZeroExt R M)) :=
  by
  simp only [pow_two, zero_eq_bot, eq_bot_iff, mul_le, mem_kerIdeal_iff_inr]
  rintro x hx y hy
  rw [hx, hy, mem_bot, inr_mul_inr]

end TrivSqZeroExt

open Ideal Ideal.Quotient TrivSqZeroExt

section GradedAlgebra

section CommSemiring

variable {R : Type _} [CommSemiring R]

variable {A : Type _} [CommSemiring A] [Algebra R A]

variable {ι : Type _} [CanonicallyOrderedAddCommMonoid ι]

variable (𝒜 : ι → Submodule R A)

theorem gradeZero_coe_smul (r : R) (x : 𝒜 0) : (↑(r • x) : A) = r • x := rfl

variable [DecidableEq ι] [GradedAlgebra 𝒜]

instance : One (𝒜 0) where
  one : 𝒜 0 := ⟨1, SetLike.one_mem_graded 𝒜⟩

instance : Mul (𝒜 0) where
  mul := fun x y => ⟨x * y, by
    convert SetLike.mul_mem_graded x.2 y.2
    rw [add_zero]⟩

@[simp]
theorem gradeZero_coe_mul (x y : 𝒜 0) : (↑(x * y) : A) = x * y := rfl

@[simp]
theorem gradeZero_val_mul (x y : 𝒜 0) : (x * y).val = x.val * y.val := rfl

omit [DecidableEq ι] [GradedAlgebra 𝒜] in
@[simp]
theorem gradeZero_coe_zero : (↑(0 : 𝒜 0) : A) = 0 := rfl

@[simp]
theorem gradeZero_coe_one : (↑(1 : 𝒜 0) : A) = 1 := rfl

theorem one_mem : (1 : A) ∈ 𝒜 0 := SetLike.one_mem_graded 𝒜

example : AddCommMonoid (𝒜 0) :=
  inferInstance

instance gradeZeroCommSemiring : CommSemiring (𝒜 0) :=
  { (inferInstance : AddCommMonoid (𝒜 0)) with
    add := (· + ·)
    zero := 0
    natCast_zero := by simp only [Nat.cast_zero]
    natCast_succ := fun n ↦ by simp only [Nat.cast_succ] -- TODO: Zulip?
    one := 1
    mul := (· * ·)
    zero_mul := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_zero, zero_mul]
    mul_zero := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_zero, mul_zero]
    mul_assoc := fun x y z => by
      ext
      simp only [gradeZero_coe_mul, mul_assoc]
    one_mul := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_one, one_mul]
    mul_one := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_one, mul_one]
    left_distrib := fun x y z => by
      ext
      simp only [Submodule.coe_add, gradeZero_coe_mul, left_distrib]
    right_distrib := fun x y z => by
      ext
      simp only [Submodule.coe_add, gradeZero_coe_mul, right_distrib]
    mul_comm := fun x y => by
      ext
      simp only [gradeZero_coe_mul, mul_comm]
     }

instance gradeZeroAlgebra : Algebra R (𝒜 0) :=
  Algebra.ofModule'
    (fun r x => by
      ext
      simp only [gradeZero_coe_mul, gradeZero_coe_smul, SetLike.val_smul,
        gradeZero_coe_one, Algebra.smul_mul_assoc, one_mul])
    (fun r x => by
      ext
      simp only [gradeZero_coe_mul, gradeZero_coe_smul, SetLike.val_smul,
        gradeZero_coe_one, Algebra.mul_smul_comm, mul_one])

/-- The projection from `A` to the degree `i` component `𝒜 i`, as an `R`-linear map. -/
def proj (i : ι) : A →ₗ[R] 𝒜 i where
  toFun a := decompose 𝒜 a i
  map_add' a b := by simp only [decompose_add, add_apply]
  map_smul' r a := by
    simp only [decompose_smul, RingHom.id_apply]
    rfl

@[simps]
def projZeroRingHom' : A →+* 𝒜 0 where
  toFun a := proj 𝒜 0 a
  map_one' := by
    ext
    simp only [proj, LinearMap.coe_mk, AddHom.coe_mk,
     decompose_of_mem_same 𝒜 (one_mem 𝒜), gradeZero_coe_one]
  map_zero' := by simp only [proj, decompose_zero, LinearMap.coe_mk, AddHom.coe_mk, zero_apply]
  map_add' _ _ := by simp only [proj, decompose_add, LinearMap.coe_mk, AddHom.coe_mk, add_apply]
  map_mul' x y := by
    ext
    simp only [proj, LinearMap.coe_mk, AddHom.coe_mk, SetLike.coe_eq_coe,
      gradeZero_coe_mul, ← GradedRing.projZeroRingHom_apply 𝒜, ← _root_.map_mul]

end CommSemiring

section CommRing

variable {R : Type _} [CommRing R]

variable {A : Type _} [CommRing A] [Algebra R A]

variable {ι : Type _} [CanonicallyOrderedAddCommMonoid ι]

variable (𝒜 : ι → Submodule R A) [DecidableEq ι] [GradedAlgebra 𝒜]

instance gradeZeroCommRing : CommRing (𝒜 0) :=
{ (inferInstance : AddCommGroup (𝒜 0)) with
    add := (· + ·)
    zero := 0
    one := 1
    mul := (· * ·)
    natCast_zero := by simp only [Nat.cast_zero]
    natCast_succ := fun n ↦ by simp only [Nat.cast_succ]
    intCast_ofNat := fun n ↦ by simp only [Int.cast_natCast]
    intCast_negSucc := fun n ↦ by rw [← Int.cast_negSucc]
    zero_mul := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_zero, zero_mul]
    mul_zero := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_zero, mul_zero]
    mul_assoc := fun x y z => by
      ext
      simp only [gradeZero_coe_mul, mul_assoc]
    one_mul := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_one, one_mul]
    mul_one := fun x => by
      ext
      rw [gradeZero_coe_mul, gradeZero_coe_one, mul_one]
    left_distrib := fun x y z => by
      ext
      simp only [Submodule.coe_add, gradeZero_coe_mul, left_distrib]
    right_distrib := fun x y z => by
      ext
      simp only [Submodule.coe_add, gradeZero_coe_mul, right_distrib]
    mul_comm := fun x y => by
      ext
      simp only [gradeZero_coe_mul, mul_comm]
     }

end CommRing

end GradedAlgebra

section GradedAlgebra

variable {R : Type _} [CommSemiring R]
variable {S : Type _} [CommSemiring S] [Algebra R S]

def GalgHom.IsHomogeneous {ι : Type _}
    {A : Type _} [CommSemiring A] [Algebra R A] (𝒜 : ι → Submodule R A)
    {B : Type _} [CommSemiring B] [Algebra S B] [Algebra R B] [IsScalarTower R S B]
    (ℬ : ι → Submodule S B) (f : A →ₐ[R] B) :=
  ∀ i a, a ∈ 𝒜 i → f a ∈ ℬ i

theorem Finsupp.prod.mem_grade
    {κ A : Type _} [AddCommMonoid κ] [DecidableEq κ] [CommSemiring A] [Algebra R A]
    (𝒜 : κ → Submodule R A) [GradedAlgebra 𝒜]
    {σ : Type _} (c : σ →₀ ℕ) (f : σ → A) (d : σ → κ)
    (hc : ∀ s ∈ c.support, f s ∈ 𝒜 (d s)) :
  (c.prod fun s e => f s ^ e) ∈ 𝒜 (c.sum fun s e => e • d s) := by
  classical
  rw [Finsupp.prod, Finsupp.sum]
  let p : Finset σ → Prop := fun s =>
    s ⊆ c.support → (s.prod fun i => f i ^ c i) ∈ 𝒜 (s.sum fun i => c i • d i)
  apply @Finset.induction_on σ p _ c.support
  · exact imp_intro (SetLike.one_mem_graded 𝒜)
  · intro a s ha hs hs'
    rw [Finset.prod_insert ha, Finset.sum_insert ha]
    exact
      SetLike.mul_mem_graded (SetLike.pow_mem_graded _ (hc a (hs' (mem_insert_self a s))))
        (hs (subset_trans (subset_insert a s) hs'))
  · exact subset_rfl

def GalgHom.isHomogeneous'
    {ι κ : Type _} (A : Type _) [CommSemiring A] [Algebra R A]
    (𝒜 : ι → Submodule R A)
    (B : Type _) [CommSemiring B] [Algebra R B] [Algebra S B] [IsScalarTower R S B]
    (ℬ : κ → Submodule S B) (φ : ι → κ) (f : A →ₐ[R] B) :=
  ∀ i a, a ∈ 𝒜 i → f a ∈ ℬ (φ i)

/-- The evaluation of a weighted homogeneous polynomial at
  elements of adequate grades is homogeneous -/
theorem GalgHom.isHomogeneous'_aeval (σ : Type _)
    {ι κ : Type _} [AddCommMonoid ι] [AddCommMonoid κ] [DecidableEq κ]
    (A : Type _) [CommSemiring A] [Algebra R A]
    (𝒜 : κ → Submodule R A) [GradedAlgebra 𝒜]
    (w : σ → ι) (φ : ι →+ κ) (f : σ → A) (h : ∀ s : σ, f s ∈ 𝒜 (φ (w s))) :
    GalgHom.isHomogeneous' (MvPolynomial σ R)
      (weightedHomogeneousSubmodule R w) A 𝒜 φ (MvPolynomial.aeval f) := by
  intro i p hp
  simp only [mem_weightedHomogeneousSubmodule, IsWeightedHomogeneous] at hp
  rw [p.as_sum, map_sum]
  apply Submodule.sum_mem
  intro c hc
  rw [aeval_monomial, ← smul_eq_mul, algebraMap_smul]
  apply Submodule.smul_mem
  convert Finsupp.prod.mem_grade 𝒜 c f _ fun s _ => h s
  rw [← hp (mem_support_iff.mp hc), Finsupp.weight_apply]
  rw [Finsupp.sum, map_sum, Finsupp.sum_of_support_subset _ le_rfl]
  apply Finset.sum_congr rfl
  . intro x _ ; simp only [map_nsmul]
  . intro s _ ; simp only [zero_smul]

end GradedAlgebra

theorem MvPolynomial.vars_X_subset {R : Type _} {σ : Type _} (n : σ) [CommSemiring R] :
    (X n : MvPolynomial σ R).vars ⊆ {n} := by
  classical
  intro u
  rw [X, mem_vars, mem_singleton]
  rintro ⟨c, hc, hc'⟩
  by_contra h'
  rw [mem_support_iff, coeff_monomial, ne_eq] at hc
  by_cases h : Finsupp.single n 1 = c
  · rw [← h, Finsupp.mem_support_iff, ne_eq, Finsupp.single_apply] at hc'
    apply hc'; rw [if_neg (Ne.symm h')]
  · apply hc; rw [if_neg h]

section

open MvPolynomial

variable {R M : Type _} [CommSemiring R]

local instance [DecidableEq R] [DecidableEq M] :
    GradedAlgebra (weightedHomogeneousSubmodule R (Prod.fst : ℕ × M → ℕ)) :=
  weightedGradedAlgebra _ _

def degree (v : ℕ × M →₀ ℕ) : ℕ :=
  finsum fun x => v x * x.1

def IsHomogeneousOfDegree (p : MvPolynomial (ℕ × M) R) (n : ℕ) : Prop :=
  ∀ v ∈ p.support, _root_.degree v = n

variable (R)

theorem variable_mem_supported (nm : ℕ × M) (hn : 0 < nm.1) :
    X nm ∈ supported R {nm : ℕ × M | 0 < nm.1} := by
  rw [mem_supported]
  refine' Set.Subset.trans (Finset.coe_subset.mpr (vars_X_subset nm)) _
  rw [coe_singleton, Set.singleton_subset_iff, Set.mem_setOf_eq]
  exact hn

def toSupported : MvPolynomial (ℕ × M) R →ₐ[R] supported R {nm : ℕ × M | 0 < nm.1} :=
  aeval fun nm : ℕ × M =>
    dite (0 < nm.1) (fun h => ⟨X nm, variable_mem_supported R nm h⟩) fun _ => 1

theorem toSupported_isHomogeneous' [DecidableEq M] [DecidableEq R] :
    GalgHom.isHomogeneous' (MvPolynomial (ℕ × M) R)
      (weightedHomogeneousSubmodule R (Prod.fst : ℕ × M → ℕ)) (MvPolynomial (ℕ × M) R)
      (weightedHomogeneousSubmodule R Prod.fst) (id : ℕ → ℕ)
      ((Subalgebra.val _).comp (toSupported R)) := by
  have heq : aeval
    ((supported R {nm : ℕ × M | 0 < nm.fst}).val.toFun ∘
        fun nm : ℕ × M =>
          if h : 0 < nm.fst
          then ⟨X nm, variable_mem_supported R nm h⟩
          else 1) =
      (supported R {nm : ℕ × M | 0 < nm.fst}).val.comp (toSupported R) :=
    by
    apply MvPolynomial.algHom_ext
    intro nm
    simp only [toSupported, AlgHom.toFun_eq_coe, Function.comp_apply, AlgHom.coe_comp, aeval_X]
  rw [← heq]
  apply GalgHom.isHomogeneous'_aeval (ℕ × M) (MvPolynomial (ℕ × M) R)
    (weightedHomogeneousSubmodule R Prod.fst) Prod.fst (AddMonoidHom.id ℕ)
  · intro nm
    simp only [mem_weightedHomogeneousSubmodule, AlgHom.toFun_eq_coe, Subalgebra.coe_val,
      Function.comp_apply, AddMonoidHom.id_apply]
    split_ifs with h
    · apply isWeightedHomogeneous_X
    · simp only [not_lt, le_zero_iff] at h
      rw [h, OneMemClass.coe_one]
      apply isWeightedHomogeneous_one

variable (M)

-- TODO: generalize
theorem eq_finsupp_single_of_degree_one [DecidableEq M]
    {d : ℕ × M →₀ ℕ} (hd : (Finsupp.weight Prod.fst) d = 1)
    (hsupp : ∀ nm ∈ d.support, 0 < nm.fst) :
  ∃ m : M, Finsupp.single (1, m) 1 = d := by
  rw [Finsupp.weight_apply, Finsupp.sum] at hd
  have hnm : ∃ nm : ℕ × M, d nm • nm.fst = 1 := by
    by_contra h0
    rw [not_exists] at h0
    have hd0 : (d.support.sum fun a : ℕ × M => d a • a.fst) = 0 := by
      rw [Finset.sum_eq_zero]
      intro nm hnm
      rw [← Nat.lt_one_iff]
      apply lt_of_le_of_ne _ (h0 nm)
      rw [← hd]
      exact Finset.single_le_sum (fun x _ => zero_le (d x • x.fst)) hnm
    rw [hd0] at hd
    exact zero_ne_one hd
  obtain ⟨nm, hnm⟩ := hnm
  rw [← hnm] at hd
  simp only [Algebra.id.smul_eq_mul, mul_eq_one] at hnm
  use nm.snd
  ext ab
  rw [Finsupp.single_apply]
  split_ifs with hab <;> rw [← hnm.2, eq_comm, Prod.mk.eta] at hab
  · rw [hab, hnm.1]
  · rw [eq_comm]
    by_contra hab'
    have hne0 : d ab * ab.fst ≠ 0 :=
      mul_ne_zero hab' (ne_of_gt (hsupp ab (Finsupp.mem_support_iff.mpr hab')))
    have hnm_mem : nm ∈ d.support := by rw [Finsupp.mem_support_iff, hnm.1]; exact one_ne_zero
    simp only [Finset.sum_eq_sum_diff_singleton_add hnm_mem, add_left_eq_self,
      Algebra.id.smul_eq_mul, sum_eq_zero_iff, mem_sdiff,
      Finsupp.mem_support_iff, mem_singleton] at hd
    exact hne0 (hd ab ⟨hab', hab⟩)

end
